### ISSUE TITLE
Cant find all locations within proximity

### ISSUE THREAD

**Issue by Clash98** [phamleduy04/texas-dps-scheduler#137] opened 2024-07-25 18:09 UTC
Tried editing the client src code from chatgpt for locations like plano and carrolton but still am not successful. Can you please help?>

**Comment by phamleduy04** [comment] 2024-07-26 06:11
Duplicate of #133. The DPS is not returning plano/carrollton location so you can't book it.

**Closed** 2024-08-06 20:52 UTC
