### ISSUE TITLE
looks like certificate is not being verfied

### ISSUE THREAD

**Issue by rayuduroshan** [phamleduy04/texas-dps-scheduler#140] opened 2024-07-28 20:28 UTC
<img width="630" alt="Screen Shot 2024-07-28 at 3 28 04 PM" src="https://github.com/user-attachments/assets/1148ce0a-cf30-44a0-823b-b230c46ee3c0">

**Comment by SSPlusUltra** [comment] 2024-07-28 22:47
yup i got the same issue, fix this please

**Comment by SSPlusUltra** [comment] 2024-07-28 22:52
![Texas DPS - Schedule Appointment — Mozilla Firefox 28-07-2024 17_48_01](https://github.com/user-attachments/assets/b9c97bab-9d3e-45e9-b2c1-c8c64bde7d6b)


I think this is happening due to the website being down.

**Comment by AryanPillai2007** [comment] 2024-07-28 23:24
Same issue for me, though the website seems to be up and running on my end. I will check back in tomorrow. 
![CleanShot 2024-07-28 at 18 24 08@2x](https://github.com/user-attachments/assets/9befd706-5676-4871-9411-6c3c9c55f16c)

**Comment by AryanPillai2007** [comment] 2024-07-29 02:13
Checked again. It is indeed down for maintenance, so I believe the program will start working again once the site is back up.


![CleanShot 2024-07-28 at 21 12 35@2x](https://github.com/user-attachments/assets/5ca3c136-f21c-4201-8207-84ee6e97bfd9)

**Comment by phamleduy04** [comment] 2024-07-29 03:41
duplicate of #138

**Closed by phamleduy04** 2024-07-29 03:41 UTC
